version: '3'

services:
  cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: UP42
    restart: always
    environment: 
      USER: "narges.mohammadi_khoshouei@stud-mail.uni-wuerzburg.de"
      PASSWORD: "St4WvWB>%^4P7f5" 
      SEARCH_RESULT_LIMIT_MAX: 2
    command: python app.py
    volumes:
      - ./:/usr/src/app
    